root: "/data/project/stemcell/shannc/output/CCA/EXOME-PAIRED"
outdir: "/data/home/shannc/chula-stem/analyses/output/cca_exome"
conda: "nf" # conda environment for reticulate
manifest: "/data/home/shannc/chula-stem/nextflow/input/manifests/cca_exome_paired.csv"
src:
  py: "/data/home/shannc/chula-stem/src/chula_stem"
  r: "/data/home/shannc/chula-stem/src/R"
cohort: "D"
get_alignments: False

extra:
  cases: ["11", "2", "4", "KBN", "KSWP", "K_Yuan", "N5"]
  multiqc_vep:
    [
      "/data/project/stemcell/shannc/output/CCA/EXOME-TUMOR_ONLY/8-D-MultiQC_data/vep.txt",
    ]

alignment_plot:
  reference_genome: "/data/project/stemcell/shannc/reference/genomes/GRCh38.p14_filtered.fasta"
  window: 50 # Width of alignment for plotting
  # Plot file dimensions
  width: 12
  height: 12
  with_prob: False
  protein_only: True # Only allow variants that affect proteins
  target_symbols:
    - "KRAS"
    - "TP53"

variant_calling:
  paired: True # Set to False if results are from `wes_tumor_only`
  min_alt_depth: null # Minimum depth that variants are counted in the plot
  # [2025-12-19 Fri] Removed because some callers don't report alt depth
  protein_only: True # Only allow variants that affect proteins
plot:
  dpi: 500
  width: 15
  height: 10

only_curated: False # Only allow named variants, regardless of type

accepted_consequence: # Only these variant types are plotted, if !`only_curated`
  # follows naming convention for variant consequences used by VEP
  # See https://grch37.ensembl.org/info/genome/variation/prediction/predicted_data.html
  - "missense_variant"
  - "frameshift_variant"
  # - "downstream_gene_variant"
  # - "upstream_gene_variant"
  # - "intron_variant"
  - "3_prime_UTR_variant"
  - "stop_gained"
  - "splice_region_variant"
  - "inframe_deletion"
  - "splice_donor_5th_base_variant"
  - "NMD_transcript_variant"

# [2025-12-17 Wed] Aj mainly wants TP53 and KRAS, others

wanted_genes: # Entries are mappings in the form gene_symbol: "chr:start-end"
  TP53: "17:7661779-7687546"
  APC: "5:112707518-112846239"
  AIM2: "1:159056129-159187843" # may contribute to immune escape
  PIK3CA: "3:179148114-179240093" # "double somatic" sCRC
  # MAPK cascade genes
  KRAS: "12:25205246-25250936"
  NRAS: "1:114704469-114716771"
  # MMR-D LS-CRC associated genes
  MLH1: "3:36993226-37050896"
  MSH2: "2:47403067-47663146"
  MSH6: "2:47695530-47810063"
  PMS2: "7:5970925-6009130"
  EPCAM: "2:47345158-47387601"

allowed_variants:
  null # Mapping of gene symbols to a list of specific variants
  # variant identifiers can be in either HGVSp or HGVSg format
  # KRAS:
  #   - "ENSP00000256078.5:p.Gly12Asp"
