__use_yte__: true
__definitions__:
  - from pathlib import Path
  - import sys
  - args = sys.argv
  - home = str(Path.home())
  - test = "test=True" in args
  - is_local = home.startswith("/home/shannc")
  - proj_root = f"{home}/Bio_SDD/chula-stem" if is_local else f"{home}/chula-stem"
  - data_root = f"{proj_root}/analyses/data_all" if is_local else "/data/project/stemcell/shannc"
  - conda_env = "stem-base" if is_local else "nf"
  - outdir = f"{data_root}/output/HCC/SCRNASEQ/cohort" if not test else f"{workdir}/test"

outdir: ?f"{proj_root}/analyses/output/pdac" # Root path for output
conda: ?conda_env # conda environment for reticulate

sample_spec:
  - manifest: ?f"{proj_root}/nextflow/input/manifests/pdac.csv" # Nextflow manifest file used for WES pipeline
    root: ?f"{data_root}/output/PDAC" # Root path of wes results
    extra: ["N45_2", "N51_2", "N56_2", "N59_2", "N68_2", "N76_1", "N80_1"]
    cohort: "cohort"
  - manifest: ?f"{proj_root}/nextflow/input/manifests/pdac_phcase1.csv"
    cohort: "PHcase"
    root: ?f"{data_root}/output/PHCase"

manifest:
src: # source directories
  py: ?f"{proj_root}/src/chula_stem"
  r: ?f"{proj_root}/src/R"

source_tag: "SOURCE"

variant_calling:
  paired: "detect" # One of "yes", "no", "detect", Set to "no" if results are from `wes_tumor_only`. Will autodetect otherwise
  min_alt_depth: 10 # Minimum depth that variants are counted in the plot
plot:
  dpi: 500
  width: 15
  height: 10

only_curated: False # Only allow named variants, regardless of type

sample_labels:
  "Waddell Class":
    palette: "Manu::Korora"
    file: ?f"{proj_root}/analyses/pdac_subtyping/waddell_subtype.tsv"
  "KRAS subtype":
    palette: "Manu::Hoiho"
    file: ?f"{proj_root}/analyses/pdac_subtyping/KRAS_imbalance_subtype.tsv"
  "Moffitt basal-like":
    palette: "Manu::Hihi"
    file: ?f"{proj_root}/analyses/pdac_subtyping/moffitt_is_basal.tsv"

accepted_consequence: # Only these variant types are plotted, if !`only_curated`
  # follows naming convention for variant consequences used by VEP
  # See https://grch37.ensembl.org/info/genome/variation/prediction/predicted_data.html
  - "missense_variant"
  - "frameshift_variant"
  - "downstream_gene_variant"
  - "upstream_gene_variant"
  - "intron_variant"
  - "3_prime_UTR_variant"
  - "stop_gained"
  - "splice_region_variant"
  - "inframe_deletion"
  - "splice_donor_5th_base_variant"
  - "NMD_transcript_variant"

wanted_genes: # Entries are mappings in the form gene_symbol: "chr:start-end"
  TP53: "17:7661779-7687546"
  APC: "5:112707518-112846239"
  AIM2: "1:159056129-159187843" # may contribute to immune escape
  PIK3CA: "3:179148114-179240093" # "double somatic" sCRC
  # MAPK cascade genes
  KRAS: "12:25205246-25250936"
  NRAS: "1:114704469-114716771"
  # MMR-D LS-CRC associated genes
  MLH1: "3:36993226-37050896"
  MSH2: "2:47403067-47663146"
  MSH6: "2:47695530-47810063"
  PMS2: "7:5970925-6009130"
  EPCAM: "2:47345158-47387601"

allowed_variants: # Mapping of gene symbols to a list of specific variants
  # variant identifiers can be in either HGVSp or HGVSg format
  KRAS:
    - "ENSP00000256078.5:p.Gly12Asp"
