:REFERENCES:
+ [1] https://support.illumina.com/content/dam/illumina-support/help/Illumina_DRAGEN_Bio_IT_Platform_v3_7_1000000141465/Content/SW/Informatics/Dragen/GPipelineAltMap_fDG.htm
+ [2] [[https://www.nature.com/articles/s41598-020-69772-8#Tab2][SomaticCombiner]]
+ [3] [[https://gatk.broadinstitute.org/hc/en-us/articles/360035531132--How-to-Call-somatic-mutations-using-GATK4-Mutect2][GATK Mutect2 Ho2]]
+ [4] [cite:@theicgc/tcgapan-canceranalysisofwholegenomesconsortiumPancancerAnalysisWhole2020]
+ [5] [[https://www.nature.com/articles/s41467-024-54387-8#Sec12][Whole-exome sequencing reveals genomic landscape of intrahepatic cholangiocarcinoma and identifies SAV1 as a potential driver]]
:END:
* Workflows
# All workflows expect an input csv file with
Outputs are prefixed with "<module_number>-" representing their order in the pipeline (roughly)

Must be submitted to the job queue
** scRNA-seq
Standard scRNA-seq raw data processing worfklow
+ QC:
+ Mapping
** WES
Workflow for variant detection on WES data inspired by https://nf-co.re/sarek/3.4.4/ and GATK best practices
*** Input
+ A csv file with four fields
  * =patient= Patient id, which should be present twice, one for the tumor and another for the normal sample
  * =fastq_1= path to raw reads
  * =fastq_2=
  * =source=  [tumor|normal]
**** Reference data
+ *WARNING:* every single resource below MUST have the same contig names
+ Genome: hg38???
  * Needs to be indexed with =bwa-mem2 index= and =samtools faidx=
    * And =gatk CreateSequenceDictionary -R <ref>=
  * Contigs must also be named =chr1=, =chr2= and so on, for use with accucopy
+ Known variants. To use with bqsr, these must be indexed with =gatk IndexFeatureFile=
  * [[http://cancer.sanger.ac.uk/cosmic][COSMIC]] (see /data/project/sirasris_shared/)
  * [[https://gnomad.broadinstitute.org/downloads#exac][Broad Institute data]]
    * gnomAD v4.1.0 Exomes for all chromosomes
    * ExAC
      * Can't use this straight from the download, it is mapped to the GRCh37/hg19 reference
  * [[https://www.ncbi.nlm.nih.gov/projects/SNP/get_html.cgi?whichHtml=overview][dbSNP]]
***** Tool-specific requirements
- VEP: uses annotation sources to predict consequence types. Can be cached and downloaded with the =INSTALL.pl= script
  * Depends on what you put for the =species= flag
  * See [[https://grch37.ensembl.org/info/docs/tools/vep/script/vep_custom.html][here]] for how to supply custom annotation data
- snpEff: needs a reference-specific database for annotation (the second argument)
  * [[https://pcingola.github.io/SnpEff/snpeff/build_db/][Instructions for custom db]]
- GATK GetPileupSummaries: a vcf file of common germline variants, with only biallelic snps and a population allele frequence (AF) info tag
- bwa-mem2: alt index for for alt-aware mapping
- MISensorPro: a homopolymers and microsatellites file prepared from the target genome
- delly: bed exclusion file denoting chromosome regions to exclude from analysis and mappability file (for CNV version)
- gridss: bed exclusion file, recommended to be from the ENCODE project
- CNVkit: with exome data, needs BED file containing baited genomic regions of the target capture kit
- Picard: with exome data, needs BED file containing baited genomic regions of the target capture kit and the target intervals file
  * The BED file must be converted into =interval_list=  format using the [[https://gatk.broadinstitute.org/hc/en-us/articles/360036883931-BedToIntervalList-Picard][BedToIntervalList]] tool
- FACETS: needs a snps file for to infer changes in allelic configuration. Docs recommend dbSNP
- Mutect2: a population-level germline resource with allele fraction, such as gnomad
*** Steps
**** Preprocessing
+ QC: =fastp= with the following routines
  * Quality filtering
  * Length filtering
  * Base correction
  * polyG tail trimming: is performed if reads are detected to NextSeq/NovaSeq
+ Read mapping to reference: =bwa-mem2=
  * This is done in an alt-aware manner, due to the benefits for variant calling when doing so [1].
    * You can get the =.alt= index file for =bwa-mem2= at
+ Marking duplicates: GATK's =MarkDuplicatesSpark=
+ Base Quality Score Recalibration: GATK =BaseRecalibrator=  and =ApplyBQSR=
  * Reports changes to base scores with =AnalyzeCovariates=
  * Both cancer and normal samples undergo BQSR with the same =known_variants= sources, which will be sources of germline variants (listed fully above)
    * See [[https://gatk.broadinstitute.org/hc/en-us/articles/360035890831-Known-variants-Training-resources-Truth-sets][here]] for the details of known variants
**** Variant calling
Callers with support for tumor-only data are marked with *T*. Note that this is not ideal and typically inflates false positives
+ Small variants
  * GATK Mutect2: somatic SNVs and indels *T*
    * Output from Mutect2 is filtered according to best practices [3]
    * *Note:* Mutect2 raw vcf files do not use the QUAL field
  * [[https://github.com/Illumina/strelka][Strelka2]]: SNVs and indels, up to a predefined maximum size of (49 bases default)
  * Notes
    * [1] observes that Mutect2 and Strelka2 are good at detecting SNVs in low VAF sites
  * [[https://github.com/wwylab/MuSE][MuSE2]]
+ Structural variants
  * [[https://github.com/xjtu-omics/msisensor-pro][MISensorPro]]: microsatellite instability *T*
  * [[https://github.com/Illumina/manta][Manta]] : Strutural variants (paired with strelka2) *T*
  * [[https://github.com/dellytools/delly][delly]], uses split-read analysis
    * *Note:* is specialized for WGS, might need to replace
  * [[https://github.com/PapenfussLab/gridss][gridss]]: uses split-read analysis *T*
    * Can also report single breakends, "breakpoints in which only one side can be unambigiously determined"
  * *Note:* do not expect this to have high number of calls due to low off-target coverage and SVs mostly occurring in noncoding regions
+ Copy number variation
  * [[https://github.com/etal/cnvkit][CNVkit]]: copy number variation (designed for hybrid capture platforms, RD-based method) *T*
    * When given hybrid-selection data, utilizes off-target reads as well as on-target to detect CNVs
  * [[https://github.com/mskcc/facets-suite][facets-suite]] (CNV detection for several omics platforms, including WES)
    * RD-based method
****  Merging results
+ Concatenate results with =bcftools concat= and report source in =SOURCE= header
**** Callset quality control
+ Possible options based on [4]
  * Tumor in normal estimation
  * Filtering out somatic mutations that are known germline sites
  * Oxidative artifact filter
+ General options (Validate this)
  * Minimum read depth in tumor, TODO: but do you need this?
    * If you impose a minimum read depth, then you may get rid of variants with low VAF
      * [4] uses a read depth of 4 and VAF of 10% for one of their tools
      * [5] requires that variants are supported by at least 4% of total reads in the tumor, and at least three reads, and less than 1% of total reads in normal
  * Maximum read depth in normal
  * Checking for PASS filter
    * *Note:* Since the INFO/FORMAT fields for the above can't be calculated with SVs, and because SV callers use different fields, SVs will only be filtered with PASS
**** Metrics
+ Tumor purity and ploidy
  * With [[https://github.com/mskcc/facets-suite][facets-suite]]
    * See [cite:@aroraFACETSFractionAlleleSpecific2022] for how to interpret
+ QC metrics from =fastp=
+ Various metrics from =Picard=
  * =CountReads=
  * =CollectAlignmentSummaryMetrics=
  * TODO: fill this up
**** Variant annotation
  (both snpEff and VEP use the sequence ontology for consequence terms (see   [[http://asia.ensembl.org/info/genome/variation/prediction/predicted_data.html#consequences][here]] ))
- [[https://github.com/Ensembl/ensembl-vep?tab=readme-ov-file#vepusage][VEP]] (SNPs, indels and SVs)
- [[https://github.com/Genotek/ClassifyCNV][ClassifyCNV]] (CNVs)
  * Attempts to estimate CNV pathogenicity using the American College of Medical Genetics and Genomics (ACMG) guidelines
    * This works by scoring the CNV, based on its overlap with protein-coding and noncoding genes, as well as with a set of dosage-sensitive genes (haploinsufficient and triplosensitive) curated by ClinGen.
      * If there is no such overlap, the algorithm checks for overlap with benign CNVs from gnomAD and DGV
  * Is cautious about assigning clinical significance, will place CNV as uncertain "if convincing data are not available"
- [[https://pcingola.github.io/SnpEff/][snpEff]] (SNPs, indels, multiple-nucleotide-polymorphisms )
  * Make sure the the chromosome names of the snpEff db and your reference genome are identical, otherwise you will get missing chromosome errors
*** Output
+ Variants with high consequence, as predicted by VEP and snpEff (both using the same terms)
****  Report format
+ TODO: format based on what P'thip sent you
+ Relevant variants table
  * Must have existing variation,
    Filter variants by those that have existing variation, ideally with clinical significance. Include read support and allele frequency in the
  * Cols for variant type, genes, read support and allele frequency too
  * Actionable drugs and mutation type if available
+ Table of mutational signatures
  * Relevant signatures - those mapped with specific processes and that have known treatments available
  * Everything else

*** Motivation
+ Using multiple variant callers is common practice, notably used in the flagship analysis of the Pan-Cancer Analysis of Whole Genomes Consortium [4]
* Dependencies
https://bedops.readthedocs.io/en/latest/index.html
samtools, bcftools

# Local Variables:
# citar-prev-references: ("aroraFACETSFractionAlleleSpecific2022")
# End:
