+ *General conventions*
  * Outputs are prefixed with a number (referred to as =module_number=) which represents their order in the pipeline (roughly)
  * Essential parameters for each pipeline are specified in a separate nextflow file (the =run_conf=  parameter) e.g. =nextflow run main.nf --run_conf CONFIG=
    * All input data e.g. reference genomes, bait files, population variation data are specified with =params.ref=, a groovy map
      * The required entries for each pipeline are detailed below under "Input"
    * See ./config/run_conf_template.config.nf and the =nextflow.config= file for more information
  * Specify tool-specific [[https://www.nextflow.io/docs/latest/process.html#directives][directives]] (e.g. container, memory usage) with =params.tools=, e.g. in a file =<pipeline_name>_tools_config.nf=. see the =config= directory for examples
    * Most tools can be passed custom command-line arguments with =task.ext.args=. The format is a Groovy list, each element either a flag or flag-value pair, which will be separated by spaces when passed with the rest of the tool's flags.
  * Cohort information to be displayed in the report (e.g. address, notes, sample collection dates) is stored in the groovy map =params.report_data=
  * Setup for =env=
    * =R_SRC=: path to directory containing this repo's R scripts
    * =PURECN=: path to PureCN scripts (should be the exdata directory of your PureCN R installation)
* General parameters
+ =defaults=: a map with default parameters for specific tools
  * =purity=, =ploidy=: in the case where purity or ploidy estimation fails or is disabled, fall back to these values
+ =create_pon=: for the paired mode of the whole-exome pipeline, whether to create a panel of normals from the normal samples. If this is enabled, the PON is automatically used in downstream filtering
+ =cohort=: name of the cohort used in summaries e.g. MultiQC
+ =genome_build=: either "hg38" or "hg17". Should be consistent with the genome fasta file
+ Output
  * =outdir=: root of all pipeline output
  * =logdir=: root to process logs
* Whole-exome sequencing (=wes.nf= )
A pipeline for detecting variants from WES data,  inspired by [[https://nf-co.re/sarek/3.4.4/][nf-core's sarek]] and GATK best practices. The final output
** Input
+ A csv file with 8 fields
  * =patient= Patient id (will be present twice on paired data)
  * =fastq_1, fastq_2= paths to raw reads
  * =source=  either tumor or normal to specify the origin of the reads on the row
  * Additional metadata fields required for compatibility with GATK tools
    * =read_group_platform_unit=
    * =read_group_platform=
    * =read_group_library=
    * =read_group_sample_name=
*** =params.ref=
+ *WARNING:* every single resource below MUST use the same contig names for chromosomes
+ =genome=: reference genome
+ =vep_species=: species of annotation sources
  * Can be cached and downloaded with the =INSTALL.pl= script
  * See [[https://grch37.ensembl.org/info/docs/tools/vep/script/vep_custom.html][here]] for how to supply custom annotation data
+ =baits=: bgzipped and indexed BED file of baited regions in exome capture kit
  * =baits_il=: the same file as =baits= converted into GATK interval list format using the [[https://gatk.broadinstitute.org/hc/en-us/articles/360036883931-BedToIntervalList-Picard][BedToIntervalList]] tool
+ =targets=: bgzipped and indexed BED file of target regions in exome capture kit
  * =targets_il=: the targets equivalent of =baits_il=
+ =baits_unzipped=: unzipped version of =baits=, defaults to =baits= without the =.gz= extension
+ =genome_blacklist=: genomic regions to ignore, such as the ENCODE blacklist
+ =known_variants=: list of file paths to known germline variants, such as dbSNP or gnomAD
+ =delly_exclude=: BED file containing genomic regions to ignore for the tool delly. Recommended to be centromeric and telomeric regions
+ =dbsnp=: bgzipped and indexed dbSNP VCF file. Filtered for somatic variants
+ =homopolymers_microsatellites=:  a homopolymers and microsatellites file prepared from the target genome with the =msisensor-pro scan= command
+ =germline=: bgzipped and indexed population-level vcf file of germline variants including the allele fraction, such as those from gnomAD
+ =pileup=: bgzipped and indexed population-level vcf file of germline variants including the allele fraction, filtered for only biallelic SNPs
+ =clingen_gene=:  file containing ClinGen gene-disease curations (see [[https://search.clinicalgenome.org/kb/downloads][Gene-Disease Validity Curations]])
+ =clingen_dosage=: file containing ClinGen dosage-sensitive gene and region data (see [[https://search.clinicalgenome.org/kb/downloads][Dosage Sensitivity Curations]])
+ =cnv_reference=: a BED file containing dbVar and gnomAD copy number variant data, generated with a custom script (=resources/prepare_cnv_repeat_data.bash=)
  * Has 7 headers: chr, start, stop, genes, source, type, accession
    * "source": which database the variant is from (dbVar:<study> or gnomAD)
    * "accession": dbVar accesssion of the variant (prefixed with =nssv=  or =essv= )
+ =msi_reference=:  the equivalent of =cnv_reference= for repetitive elements, generated with the same script; a BED file containing dbVar and clinVar repetitive element data
+ =civic_cache=: path to json file containing cached calls to Civic API (is automatically generated and updated if it doesn't exist)
+ =pandrugs2_cache=: path to json file containing cached calls to Pandrugs2 API (is automatically generated and updated if it doesn't exist)
+ =pon= : path to a panel of normals. Any variants found in this file will be excluded from the final callset
+ *PureCN-specific parameters*
  * In =params.ref=
    * =snp_blacklist=: vcf file containing snps that PureCN should ignore
    * =mappability=: path to an "rtracklayer parsable file with a mappability score in the first meta data column". See header 2 of [2] for more information
    * =purecn_normaldb=: path to a pre-generated normaldb e.g. for in tumor-only mode
  * =interval_padding=: a Mutect2 parameter, pads exome intervals to increase the number of heterozygous SNPs called. Set this to 50-75, unless for very high coverages, where you can set it to 200 [2]
** Steps
*** Preprocessing
+ Quality control ([[https://github.com/OpenGene/fastp][fastp]])
  + =fastp= is an all-in-one FASTQ preprocessing tool; base-quality filtering, length filtering, and base correction are enabled
    * If the reads are detected to be generated with the NextSeq or NovaSeq platforms, polyG tail trimming is also performed
+ Read mapping to reference [[https://github.com/bwa-mem2/bwa-mem2][(bwa-mem2)]]
+ Marking PCR duplicates ([[https://gatk.broadinstitute.org/hc/en-us/articles/360037052812-MarkDuplicates-Picard][GATK MarkDuplicates]])
+ Base Quality Score Recalibration ([[https://gatk.broadinstitute.org/hc/en-us/articles/360035890531-Base-Quality-Score-Recalibration-BQSR][GATK BaseRecalibrator, ApplyBQSR]])
  * Both tumor and normal samples undergo BQSR with the same parameter for =known_variants=
    * See [[https://gatk.broadinstitute.org/hc/en-us/articles/360035890831-Known-variants-Training-resources-Truth-sets][here]] for the details about this parameter
*** Variant calling
Find variants with multiple, intended to be used as an additional form of callset quality control (see below). Specific callers can be disabled if needed, but enable at least one from each category
+ Small variants ( [[https://gatk.broadinstitute.org/hc/en-us/articles/360037593851-Mutect2][Mutect2]], [[https://github.com/Illumina/strelka][Strelka2]], [[https://github.com/wwylab/MuSE][MuSE2]], [[https://luntergroup.github.io/octopus/][Octopus]], [[https://github.com/HKU-BAL/ClairS][ClairS]])
+ Microsatellite instability ([[https://github.com/xjtu-omics/msisensor-pro][MISensorPro]])
+ Structural variants ([[https://github.com/Illumina/manta][Manta]], [[https://github.com/dellytools/delly][delly]], [[https://github.com/PapenfussLab/gridss][gridss]])
+ Copy number variants ([[https://github.com/lima1/PureCN][PureCN]], [[https://github.com/etal/cnvkit][CNVkit]], [[https://github.com/mskcc/facets-suite][facets-suite]])
  * The subworkflow used for PureCN follows the best practices outlined in [2], which uses (unfiltered) Mutect2 calls as the source of SNPs and performs internal segmentation.
  * For optimal results, you should either provide a panel of normals or create one in the paired workflow so that PureCN can generate a mapping bias file.
*** Callset quality control
+ Filters for small and structural variants include requiring specified filter fields (PASS by default) and identification by a minimum number of variants
+ You can also filter small variants* with minimum read depth in tumor, maximum read depth in normal and minimum VAF
  * *Not possible for structural variants as the required INFO/FORMAT fields are not provided from SV callers
+ Configured with =params.qc= , =params.small_qc=  and =params.sv_qc=
#+begin_src nextflow
params.qc = ["accepted_filters": ["PASS"],
                "min_tumor_depth": 10,
                "min_callers": 2,
                "max_normal_depth": 10,
                "min_VAF": 0.10]
#+end_src
*** Variant annotation
- [[https://github.com/Ensembl/ensembl-vep?tab=readme-ov-file#vepusage][VEP]] (SNPs, indels and SVs)
- [[https://github.com/Genotek/ClassifyCNV][ClassifyCNV]] (CNVs)
- Genes overlapping unstable regions detected by msisensor-pro are also reported
*** Misc. output
+ The pipeline collects various metrics, including..
  * Estimation of tumor purity and ploidy (PureCN)
  * Sequencing metrics ([[https://github.com/brentp/mosdepth][mosdepth]], [[https://gatk.broadinstitute.org/hc/en-us/articles/360036856051-CollectHsMetrics-Picard][Picard CollectHsMetrics]], [[https://gatk.broadinstitute.org/hc/en-us/articles/360042476752-CollectAlignmentSummaryMetrics-Picard][CollectAlignmentSummaryMetrics]])
  * QC metrics (=fastp=,  [[https://gatk.broadinstitute.org/hc/en-us/articles/360037066912-AnalyzeCovariates][GATK AnalyzeCovariates]])
  * [[https://github.com/MultiQC/MultiQC][MultiQC]] summarizes the latter two metrics + COSMIC mutational signature fitting ([[https://github.com/AlexandrovLab/SigProfilerAssignment?tab=readme-ov-file][SigProfilerAssignment]])
** Tumor-only mode (=wes_tumor_only.nf=)
+ The pipeline has support for tumor-only WES datasets with the following variant callers
  * Small variants: Mutect2, Octopus, [[https://github.com/HKU-BAL/ClairS-TO][ClairS-TO]]
  * Structural variants: gridss, Manta
  * Copy number variants: cnvkit, PureCN
    * Without tumor samples, copy number calls will have lower accuracy, but large-scale CNVs should still be detected [1]
    * PureCN requires a normaldb generated from process-matched normal samples, which can be generated automatically from a run of the paired mode
* RNA-seq
TODO
** Input
** Steps
*** Preprocessing
+ QC:
  * =fastp= with quality, length filtering, base correction
+ Marking duplicates: GATK's =MarkDuplicatesSpark=
*** Read quantification
+ =kallisto= - a pseudoalignment program that quantifies reads at the transcript level
  * These will be collapsed into gene-level abundance estimates with [[https://bioconductor.org/packages/release/bioc/html/tximport.html][tximport]]
*** Fusion detection

* VAR
:REFERENCES:
+ [1] [[https://cnvkit.readthedocs.io/en/stable/pipeline.html#with-no-control-samples][CNVkit documentation: Copy number calling pipeline]]
+ [2] [[https://bioconductor.org/packages/release/bioc/vignettes/PureCN/inst/doc/Quick.html#2_Prepare_environment_and_assay-specific_reference_files][PureCN best practices]]
:END:
