root: "/data/project/stemcell/shannc/output/CRC/EXOME-PAIRED"
outdir: "/data/home/shannc/chula-stem/analyses/output/crc_exome"
conda: "nf" # conda environment for reticulate
manifest: "/data/home/shannc/chula-stem/nextflow/input/manifests/crc_exome_paired.csv"
src:
  py: "/data/home/shannc/chula-stem/src/chula_stem"
  r: "/data/home/shannc/chula-stem/src/R"
cohort: "CEN2"

extra:
  cases: ["CEN2_N18", "CEN2_N27", "D-CEN2-N20", "D-CEN2-N22"]
