configfile: "../env.yaml"
configfile: "config.yaml"


include: "../common.smk"


import pandas as pd


outdir = f"{config['out']['root']}/crc_exome"
store = f"{config['out']['repos']}/crc_exome"
data_path = f"{config['out']['nf']}/CRC/EXOME-PAIRED"
sample_sheet = pd.read_csv(f"{config['nf_input']}/crc_exome_paired.csv")
cohort = config["cohort"]


cases = set(sample_sheet["patient"])

to_ignore = set()
for c in cases:
    if not Path(f"{data_path}/{c}/annotations/7-{c}-VEP_small.vcf.gz").exists():
        to_ignore.add(c)

cases = list(cases - to_ignore)


rule all:
    input:
        gene_metrics=f"{outdir}/{DATE}/gene_metrics.png",
        vaf_separate=f"{outdir}/{DATE}/vaf_separate.png",
        vaf=f"{outdir}/{DATE}/vaf.png",


rule get_vep:
    output:
        tsvs=expand("{s}/vcfs/{sample}.tsv", s=outdir, sample=cases),
        vcfs=[temp(f) for f in expand("{s}/vcfs/{sample}.vcf", s=outdir, sample=cases)],
        combined=f"{outdir}/vcfs/combined.tsv",
    params:
        outdir=f"{outdir}/vcfs",
        cases=cases,
        data_path=data_path,
        genes=config["wanted_genes"],
    script:
        "select_genes.R"


rule get_sbs:
    params:
        data_path=data_path,
    output:
        f"{outdir}/sbs.csv",
    script:
        "get_sbs.py"


rule get_tmb:
    input:
        f"{data_path}/{cohort}-MultiQC_data/vep.txt",
    output:
        f"{outdir}/tumor_mutational_burden.tsv",
    script:
        "get_tmb.R"


rule vaf_plot:
    input:
        combined_vep=rules.get_vep.output.combined,
        sbs=rules.get_sbs.output,
        tmb=rules.get_tmb.output,
    params:
        wanted_genes=config["wanted_genes"].keys(),
    output:
        gene_metrics=rules.all.input.gene_metrics,
        vaf_separate=rules.all.input.vaf_separate,
        vaf=rules.all.input.vaf,
