#!/bin/bash

# Created by argbash-init v2.10.0
# ARG_POSITIONAL_SINGLE([mixtcr_dir])
# ARG_POSITIONAL_SINGLE([model])
# ARG_POSITIONAL_SINGLE([input])
# ARG_POSITIONAL_SINGLE([output])
# ARG_OPTIONAL_SINGLE([conda_dir],[],[Path to conda installation])
# ARG_OPTIONAL_SINGLE([conda_env],[],[Conda environment to run MixTCR with])
# ARG_DEFAULTS_POS([])
# ARG_HELP([<The general help message of my script>])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info

die() {
    local _ret="${2:-1}"
    test "${_PRINT_HELP:-no}" = yes && print_help >&2
    echo "$1" >&2
    exit "${_ret}"
}

begins_with_short_option() {
    local first_option all_short_options='h'
    first_option="${1:0:1}"
    test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
_arg_mixtcr_dir=
_arg_model=
_arg_input=
_arg_output=
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_conda_dir=
_arg_conda_env=

print_help() {
    printf '%s\n' "<The general help message of my script>"
    printf 'Usage: %s [--conda_dir <arg>] [--conda_env <arg>] [-h|--help] <mixtcr_dir> <model> <input> <output>\n' "$0"
    printf '\t%s\n' "--conda_dir: Path to conda installation (no default)"
    printf '\t%s\n' "--conda_env: Conda environment to run MixTCR with (no default)"
    printf '\t%s\n' "-h, --help: Prints help"
}

parse_commandline() {
    _positionals_count=0
    while test $# -gt 0; do
        _key="$1"
        case "$_key" in
        --conda_dir)
            test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
            _arg_conda_dir="$2"
            shift
            ;;
        --conda_dir=*)
            _arg_conda_dir="${_key##--conda_dir=}"
            ;;
        --conda_env)
            test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
            _arg_conda_env="$2"
            shift
            ;;
        --conda_env=*)
            _arg_conda_env="${_key##--conda_env=}"
            ;;
        -h | --help)
            print_help
            exit 0
            ;;
        -h*)
            print_help
            exit 0
            ;;
        *)
            _last_positional="$1"
            _positionals+=("$_last_positional")
            _positionals_count=$((_positionals_count + 1))
            ;;
        esac
        shift
    done
}

handle_passed_args_count() {
    local _required_args_string="'mixtcr_dir', 'model', 'input' and 'output'"
    test "${_positionals_count}" -ge 4 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 4 (namely: $_required_args_string), but got only ${_positionals_count}." 1
    test "${_positionals_count}" -le 4 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 4 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}

assign_positional_args() {
    local _positional_name _shift_for=$1
    _positional_names="_arg_mixtcr_dir _arg_model _arg_input _arg_output "

    shift "$_shift_for"
    for _positional_name in ${_positional_names}; do
        test $# -gt 0 || break
        eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
        shift
    done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash

# vvv  PLACE YOUR CODE HERE  vvv

if [[ -n "${_arg_conda_dir}" && -n "${_arg_conda_env}" ]]; then
    source "${_arg_conda_dir}/etc/profile.d/conda.sh"
    conda activate "${_arg_conda_env}"
fi

cur=$(pwd)
if [[ ! -d "${_arg_mixtcr_dir}" ]]; then
    echo "Given MixTCR directory doesn't exist!"
    exit 1
fi
input=$(realpath "${_arg_input}")
output=$(realpath "${_arg_output}")
cd "${_arg_mixtcr_dir}" || exit 0
python MixTCRpred.py -m "${_arg_model}" --input "${input}" --output "${output}"
cd "${cur}" || exit 0

# ^^^  TERMINATE YOUR CODE BEFORE THE BOTTOM ARGBASH MARKER  ^^^

# ] <-- needed because of Argbash
