import json
from datetime import date
from pathlib import Path


configfile: "env.yaml"


def add_root(file):
    root = config.get("root")
    if root:
        return f"{root}/{file}"
    return file


DATE = config.get("date", "no_date")

OUT = add_root(f"{config.get('output')}/{DATE}")

runs = {k: add_root(v) for k, v in config["bd_results"].items()}


refs_to_get, references = {}, {}
for ref, p in config["reference_files"].items():
    path = Path(add_root(p))
    adata_file = path.with_suffix(".h5ad")
    if not adata_file.exists():
        refs_to_get[ref] = adata_file
    references[ref] = adata_file

cell_annotation_results = {}
if config["annotate_cells"]["cellassign"]["run"]:
    cell_annotation_results.update(
        {
            "elbo_validation": f"{OUT}/cellassign/elbo_validation.png",
            "predictions_raw": f"{OUT}/cellassign/predictions_raw.csv",
            "predictions": f"{OUT}/cellassign/predictions.csv",
        }
    )


plots = {
    "alpha_diversity": f"{OUT}/plots/alpha_diversity.png",
    "public_private": f"{OUT}/plots/public_private.png",
    "top_clones": f"{OUT}/top_clones.csv",
    "expansion": f"{OUT}/plots/clone_expansion",
    "ct_abundance": f"{OUT}/plots/cell_type_abundance",
}


rule all:
    input:
        **refs_to_get,
        **cell_annotation_results,
        **plots,
        combined=f"{OUT}/combined.h5mu",


rule prepare_references:
    params:
        refs_to_get=refs_to_get,
    output:
        refs_to_get.values(),
    script:
        "prepare_data.py"


rule load_runs:
    output:
        f"{OUT}/combined.h5mu",
    params:
        runs=runs,
    script:
        "prepare_data.py"


rule annotate_cells:
    output:
        **cell_annotation_results,
    input:
        rules.load_runs.output,
    script:
        "prepare_data.py"


rule scirpy_query:
    input:
        rules.load_runs.output,
        refs_to_get.values(),
    params:
        references=references,
        outdir=f"{OUT}/reference_comparison/scirpy",
    output:
        expand("{o}/reference_comparison/scirpy/{r}.h5ad", o=OUT, r=references.keys()),
        expand("{o}/reference_comparison/scirpy/{r}.csv", o=OUT, r=references.keys()),
    script:
        "analyses.py"


rule make_reports:
    input:
        rules.load_runs.output,
    params:
        plotdir=f"{OUT}/plots",
        outdir=f"{OUT}",
    output:
        alpha_diversity=f"{OUT}/plots/alpha_diversity.png",
        public_private=f"{OUT}/plots/public_private.png",
        top_clones=f"{OUT}/top_clones.csv",
        expansion=directory(f"{OUT}/plots/clone_expansion"),
        ct_abundance=directory(f"{OUT}/plots/cell_type_abundance"),
    script:
        "plotting.py"
