import json
from datetime import date
from pathlib import Path


configfile: "env.yaml"


TODAY = date.today().isoformat()
DATE = config.get("date", TODAY)

OUT = config.get("output")

runs = config["bd_results"]


refs_to_get, references = {}, {}
for ref, p in config["reference_files"].items():
    path = Path(p)
    adata_file = path.with_suffix(".h5ad")
    if not adata_file.exists():
        refs_to_get[ref] = adata_file
    references[ref] = adata_file

cell_annotation_results = {}
if config["annotate_cells"]["cellassign"]:
    cell_annotation_results.update(
        {
            "elbo_validation": f"{OUT}/cellassign/elbo_validation.png",
            "predictions_raw": f"{OUT}/cellassign/predictions_raw.csv",
            "predictions": f"{OUT}/cellassign/predictions.csv",
        }
    )


rule all:
    input:
        **refs_to_get,
        **cell_annotation_results,
        combined_adata=f"{OUT}/combined.h5ad",


rule prepare_references:
    params:
        refs_to_get=refs_to_get,
    output:
        refs_to_get.values(),
    script:
        "prepare_data.py"


rule load_runs:
    output:
        f"{OUT}/combined.h5mu",
    script:
        "prepare_data.py"


rule annotate_cells:
    output:
        **cell_annotation_results,
    input:
        rules.load_runs.output,
    script:
        "prepare_data.py"


rule scirpy_query:
    input:
        rules.load_runs.output,
        refs_to_get.values(),
    params:
        references=references,
        outdir=f"{OUT}/reference_comparison/scirpy",
    output:
        expand("{o}/reference_comparison/scirpy/{r}.h5ad", o=OUT, r=references.keys()),
        expand("{o}/reference_comparison/scirpy/{r}.csv", o=OUT, r=references.keys()),
    script:
        "analyses.py"


# rule make_plots
