import json
from datetime import date
from pathlib import Path
import pandas as pd


configfile: "env.yaml"


TODAY = date.today().isoformat()
DATE = config.get("date", TODAY)

sample_sheet = pd.read_csv(config["manifest"])
extra = config.get("extra", {})
data_path = config["root"]
outdir = f'{config["outdir"]}/{DATE}'

cases = set(list(sample_sheet["patient"]) + extra.get("cases", []))

sample_maps = {}
for c in cases:
    case_path = Path(data_path).joinpath(c).joinpath("annotations")
    vep_path = case_path.joinpath(f"8-{c}-VEP_small.tsv")
    msi_path = case_path.joinpath(f"8-{c}-CR_MSI.tsv")
    cnv_path = case_path.joinpath(f"8-{c}-CR_CNV.tsv")
    cns = f"5-{c}-Cnvkit/5-{c}-Cnvkit.call.cns"
    cns_path = Path(data_path).joinpath(f"{c}/variant_calling/{cns}")
    if not cns_path.exists():
        cns_path = Path(data_path).joinpath(f"{c}/paired/{cns}")
    sample_maps[c] = {}
    for group, f in zip(
        ["cns", "cnv", "vep", "msi"], [cns_path, cnv_path, vep_path, msi_path]
    ):
        if f.exists():
            sample_maps[c][group] = str(f.absolute())
        else:
            print(f"WARNING: {group} file {f} does not exist for case {c}!")

encoding_styles = config["encoding_styles"]

feature_dir = f"{outdir}/features"

feature_files = {
    "protein_features": {
        d: expand(
            "{o}/{drug}_{s}.tsv",
            o=feature_dir,
            drug=d,
            s=encoding_styles,
        )
        for d in config["per_drug_encoding"].keys()
    }
}


rule encode_features:
    """Generate tsv files where samples are"""
    output:
        **feature_files["protein_features"],
        jsons=[
            temp(f"{outdir}/feature_config_{style}.json") for style in encoding_styles
        ],
    run:
        for drug, sym in config["per_drug_encoding"].items():
            for style in encoding_styles:
                conf_file = f"{outdir}/feature_config_{style}.json"
                outfile = f"{feature_dir}/{drug}_{style}.tsv"
                symbols = {}
                if config["limit_symbols"].get(style, True):
                    for k, v in sym.items():
                        if isinstance(v, str):
                            with open(v, "r") as f:
                                symbols[k] = f.read().splitlines()
                        else:
                            symbols[k] = v
                dct = {
                    "transcript_id2uniprot": config["transcript_id2uniprot"],
                    "samples": sample_maps,
                    "only_symbols": symbols,
                    "features": config["uniprot_features"],
                    "encoding_method": style,
                    "allowed_consequence": config["allowed_consequence"],
                }
                with open(conf_file, "w") as f:
                    json.dump(dct, f)
                shell(f"Rscript encode_features.R -i {conf_file} -o {outfile}")


# rule regress_feature_drug_response:
#     """Fit a model that regresses drug response on variants to specific protein features"""
#     ...
# TODO: enrichment analyses on drug sensitivity groups
# TODO: cnv analyses
