import json
from datetime import date
from pathlib import Path
import pandas as pd


configfile: "env.yaml"


TODAY = date.today().isoformat()
DATE = config.get("date", TODAY)

sample_sheet = pd.read_csv(config["manifest"])
extra = config.get("extra", {})
data_path = config["root"]
outdir = f'{config["outdir"]}/{DATE}'

cases = set(list(sample_sheet["patient"]) + extra.get("cases", []))

sample_maps = {}
for c in cases:
    case_path = Path(data_path).joinpath(c).joinpath("annotations")
    vep_path = case_path.joinpath(f"8-{c}-VEP_small.tsv")
    msi_path = case_path.joinpath(f"8-{c}-CR_MSI.tsv")
    cnv_path = case_path.joinpath(f"8-{c}-CR_CNV.tsv")
    cns = f"5-{c}-Cnvkit/5-{c}-Cnvkit.call.cns"
    cns_path = Path(data_path).joinpath(f"{c}/variant_calling/{cns}")
    if not cns_path.exists():
        cns_path = Path(data_path).joinpath(f"{c}/paired/{cns}")
    sample_maps[c] = {}
    for group, f in zip(
        ["cns", "cnv", "vep", "msi"], [cns_path, cnv_path, vep_path, msi_path]
    ):
        if f.exists():
            sample_maps[c][group] = str(f.absolute())
        else:
            print(f"WARNING: {group} file {f} does not exist for case {c}!")

d_encoding_styles = config["per_drug_encoding_styles"]

feature_dir = f"{outdir}/features"

# * Output

feature_files = {
    "per_drug": {  # For using a drug-specific feature list
        d: expand(
            "{o}/{drug}_{s}.tsv",
            o=feature_dir,
            drug=d,
            s=d_encoding_styles,
        )
        for d in config["per_drug_encoding"].keys()
    },
    "all": {
        "binary": f"{feature_dir}/binary.tsv",
        "vep_consequence": f"{feature_dir}/vep_consequence.tsv",
    },
}

analysis_results = {
    "binary": {
        resp: f"{outdir}/binary_tests/{resp}.tsv" for resp in config["response_cols"]
    },
    "ora": [dir(f"{outdir}/enrichment_analyses/{d}") for d in config["response_cols"]],
}


# * Helper functions


def copy_config(out):
    with open(out, "w") as f:
        json.dump(config, f)


def write_encoding_config(out, **kwargs):
    dct = {
        "transcript_id2uniprot": config["transcript_id2uniprot"],
        "samples": sample_maps,
        "features": config["uniprot_features"],
        "allowed_consequence": config["allowed_consequence"],
    }
    dct.update(kwargs)
    with open(out, "w") as f:
        json.dump(dct, f)


# * Rules


rule all:
    input:
        *analysis_results["binary"].values(),
        mutation_summary=f"{outdir}/mutation_summary.tsv",


rule mutation_summary:
    output:
        rules.all.input.mutation_summary,
        config=temp(f"{outdir}/tmp.json"),
    run:
        with open(output.config, "w") as f:
            json.dump({"samples": sample_maps}, f)
        shell(f"Rscript encode_features.R -i {output.config} -o {output[0]} -s")


rule encode_features:
    """Generate tsv files where samples are"""
    output:
        **feature_files["per_drug"],
        **feature_files["all"],
        jsons=[
            temp(f"{outdir}/feature_config_{style}.json")
            for style in d_encoding_styles
        ],
    run:
        for encoding, f in feature_files["all"].items():
            conf_file = f"{outdir}/feature_config_{encoding}.json"
            write_encoding_config(out=conf_file, encoding_method=encoding)
            shell(f"Rscript encode_features.R -i {conf_file} -o {f}")
        for drug, sym in config["per_drug_encoding"].items():
            for style in d_encoding_styles:
                conf_file = f"{outdir}/feature_config_{style}.json"
                outfile = f"{feature_dir}/{drug}_{style}.tsv"
                symbols = {}
                for k, v in sym.items():
                    if isinstance(v, str):
                        with open(v, "r") as f:
                            symbols[k] = f.read().splitlines()
                    else:
                        symbols[k] = v
                dct = write_encoding_config(
                    out=conf_file, only_symbols=symbols, encoding_method=style
                )
                shell(f"Rscript encode_features.R -i {conf_file} -o {outfile}")


# rule regress_feature_drug_response:
#     """Fit a model that regresses drug response on variants to specific protein features"""
#     ...
# TODO: enrichment analyses on drug sensitivity groups
# TODO: cnv analyses
