configfile: "env.yaml"  # A config file must be provided


import pandas as pd
from datetime import date

TODAY = date.today().isoformat()
DATE = config.get("date", TODAY)

"""
Generate VAF figures from the results of the wes/wes_tumor_only pipeline

See env_template.yaml for what to specify
"""


outdir = f"{config['outdir']}/{DATE}"


def samples_setup() -> tuple[pd.DataFrame, dict]:
    tmp = []
    for spec in config["sample_spec"]:
        if "manifest" not in spec:
            raise ValueError("Manifest must be specified")
        if "root" not in spec:
            raise ValueError("Root must be specified")
        root = spec["root"]
        df = pd.read_csv(spec["manifest"]).assign(root=root)
        if rename := spec.get("rename"):
            df.loc[:, "patient"] = df["patient"].replace(rename)
        if extra := spec.get("extra"):
            df = pd.concat(df, pd.DataFrame({"patient": extra, "root": root}))
        cases = df["patient"]
        to_ignore = set()
        for c in cases:
            if not Path(f"{root}/{c}/annotations/7-{c}-VEP_small.vcf.gz").exists():
                to_ignore.add(c)
        if to_ignore:
            print(f"No VEP data available for the following: {to_ignore}")
            df = df[~df["patient"].isin(to_ignore), :]
        tmp.append(df)
    combined = pd.concat(tmp)
    if (combined["patient"].value_counts() > 1).any():
        print(combined)
        raise ValueError(
            "Duplicate sample names detected, try setting the `rename` key"
        )
    return combined, dict(zip(combined["patient"], combined["root"]))


manifest, sample2root = samples_setup()
samples = manifest["patient"]
vcf_dir = f"{outdir}/vcfs"
align_dir = f"{outdir}/alignments"


VAF_OUT = {
    "gene_metrics": f"{outdir}/gene_metrics.png",
    "vaf_separate": f"{outdir}/vaf_separate.png",
    "vaf": f"{outdir}/vaf.png",
    "plot_data": f"{outdir}/vaf_plot_data.tsv",
    "variant_table": f"{outdir}/variant_table.html",
    # BUG: this really should be pdf, but would need chrome installed on server
}
ALIGN_OUT = {"alignments": expand("{o}/{c}", o=align_dir, c=samples)}

if config.get("get_alignments"):
    print("Creating alignment plot only...")
    TARGETS = ALIGN_OUT
else:
    TARGETS = VAF_OUT


rule all:
    input:
        **TARGETS,


rule get_vep:  # Retrieve vep results for select genes
    output:
        tsvs=expand("{v}/{sample}.tsv", v=vcf_dir, sample=samples),
        vcfs=[temp(f) for f in expand("{v}/{sample}.vcf", v=vcf_dir, sample=samples)],
        combined=f"{vcf_dir}/combined.tsv",
    params:
        outdir=vcf_dir,
        cases=samples,
        data_mapping=sample2root,
        genes=config["wanted_genes"],
    script:
        "select_genes.R"


rule get_sbs:  # Get single-base-substitution statistics
    params:
        data_mapping=sample2root,
        cases=samples,
    output:
        f"{outdir}/sbs.tsv",
    script:
        "get_sbs.py"


multiqc_veps = [
    f"{s['root']}/8-{s['cohort']}-MultiQC_data/vep.txt" for s in config["sample_spec"]
]


rule get_tmb:  # Retrieve tumor mutational burden counts
    input:
        multiqc_veps,
    output:
        f"{outdir}/tumor_mutational_burden.tsv",
    script:
        "get_tmb.R"


rule vaf_plot:  # Assemble plot
    input:
        combined_vep=rules.get_vep.output.combined,
        sbs=rules.get_sbs.output,
        tmb=rules.get_tmb.output,
    params:
        wanted_genes=config["wanted_genes"].keys(),
    output:
        gene_metrics=VAF_OUT["gene_metrics"],
        vaf_separate=VAF_OUT["vaf_separate"],
        vaf=VAF_OUT["vaf"],
        plot_data=VAF_OUT["plot_data"],
    script:
        "vaf_plot.R"


rule variant_table:
    input:
        rules.get_vep.output.combined,
    output:
        VAF_OUT["variant_table"],
    script:
        "variant_table.R"


rule alignment_plot:
    input:
        vcfs=rules.get_vep.output.tsvs,
    output:
        plots=directory(expand("{o}/{c}", o=align_dir, c=samples)),
    params:
        outdir=align_dir,
        data_mapping=sample2root,
    log:
        f"{align_dir}/alignment_plot.log",
    script:
        "alignment_plot.R"
