configfile: "env.yaml"


import pandas as pd
from datetime import date

TODAY = date.today().isoformat()
DATE = config.get("date", TODAY)

"""
Generate VAF figures from the results of the wes/wes_tumor_only pipeline

See config.yaml for what to specify
"""


outdir = f"{config['outdir']}/crc_exome"
data_path = f"{config['root']}/CRC/EXOME-PAIRED"
sample_sheet = pd.read_csv(f"{config['manifest']}/crc_exome_paired.csv")

cohort = config.get("cohort", "cohort")


cases = set(sample_sheet["patient"])

to_ignore = set()
for c in cases:
    if not Path(f"{data_path}/{c}/annotations/7-{c}-VEP_small.vcf.gz").exists():
        to_ignore.add(c)

cases = list(cases - to_ignore)
vcf_dir = f"{outdir}/{DATE}/vcfs"


rule all:
    input:
        gene_metrics=f"{outdir}/{DATE}/gene_metrics.png",
        vaf_separate=f"{outdir}/{DATE}/vaf_separate.png",
        vaf=f"{outdir}/{DATE}/vaf.png",


rule get_vep:  # Retrieve vep results for select genes
    output:
        tsvs=expand("{v}/{sample}.tsv", v=vcf_dir, sample=cases),
        vcfs=[temp(f) for f in expand("{v}/{sample}.vcf", v=vcf_dir, sample=cases)],
        combined=f"{vcf_dir}/combined.tsv",
    params:
        outdir=vcf_dir,
        cases=cases,
        data_path=data_path,
        genes=config["wanted_genes"],
    script:
        "select_genes.R"


rule get_sbs:  # Get single-base-substitution statistics
    params:
        data_path=data_path,
    output:
        f"{outdir}/sbs.tsv",
    script:
        "get_sbs.py"


rule get_tmb:  # Retrieve tumor mutational burden counts
    input:
        f"{data_path}/{cohort}-MultiQC_data/vep.txt",
    output:
        f"{outdir}/tumor_mutational_burden.tsv",
    script:
        "get_tmb.R"


rule vaf_plot:  # Assemble plot
    input:
        combined_vep=rules.get_vep.output.combined,
        sbs=rules.get_sbs.output,
        tmb=rules.get_tmb.output,
    params:
        wanted_genes=config["wanted_genes"].keys(),
    output:
        gene_metrics=rules.all.input.gene_metrics,
        vaf_separate=rules.all.input.vaf_separate,
        vaf=rules.all.input.vaf,
    script:
        "vaf_plot.R"
