__use_yte__: true
__definitions__:
  - from pathlib import Path
  - import sys
  - args = sys.argv
  - home = str(Path.home())
  - test = "test=True" in args
  - is_local = home.startswith("/home/shannc")
  - proj_root = f"{home}/Bio_SDD/chula-stem" if is_local else f"{home}/chula-stem"
  - tpredict = f"{home}/Bio_SDD/too-predict" if is_local else f"{home}/too-predict"
  - data_root = f"{proj_root}/analyses/data_all" if is_local else "/data/project/stemcell/shannc"
  - workdir = f"{proj_root}/analyses/scrnaseq_hcc"
  - outdir = f"{data_root}/output/HCC/SCRNASEQ/cohort" if not test else f"{workdir}/test"

test: ?test

manifest_file_key: null # Set to null to take from the cellranger directory
conda: stem-base
args: ?args
workdir: ?workdir
r_src: ?f"{proj_root}/src/R"
outdir: ?outdir
data_root: ?f"{data_root}/output/HCC/SCRNASEQ"
logdir: ?f"{workdir}/logs" if not test else f"{workdir}/test/logs"
manifest: ?f"{this['workdir']}/manifest.csv"

exclude_from_clustering: # We're excluding normals and treated samples from clustering routines since the goal in those is to find tumor subtypes/tumor-specific cell types
  # Cells from these samples will have their cluster values set to NA
  - H19_tumor-iacs
  - H8_tumor-iacs
  - H8_tumor-oligomycin
  - H8_tumor-pp
  - HCCN1_normal-control
  - HCCN22_normal-control
  - HCC5_normal-control

files:
  combined: ?f"{this['outdir']}/combined.h5ad"
  permissive_features: ?f"{this['outdir']}/permissive_features.txt"
  passed_qc: ?f"{this['outdir']}/filtered.h5ad"
  failed_qc: ?f"{this['outdir']}/failed_qc.h5ad"
  extras: # | character separates sample type
    HCC5|normal|control: ?f"{data_root}/output/HCC/SCRNASEQ/HCC5/processed/mnt-nas-thanakornj-liverOrganoid-SCTmatrix-HCC_N5_normal.h5ad"
    HCCN22|normal|control: ?f"{data_root}/output/HCC/SCRNASEQ/HCCN22/processed/mnt-nas-thanakornj-liverOrganoid-SCTmatrix-HCC_N22_normal.h5ad"
    HCCN1|normal|control: ?f"{data_root}/output/HCC/SCRNASEQ/HCCN1/processed/mnt-nas-thanakornj-liverOrganoid-SCTmatrix-HCC_N1_normal.h5ad"

rng: 4972

# * Dimensionality reduction
DR:
  n_pcs: 50
  methods:
    umap:
      # vary: ["n_neighbors", []]
      vary: ?["n_neighbors", list(range(100, 5000, 500)) if not test else []]
      kws:
        random_state: ?this['rng']
    t-sne_tdr:
      vary: ["perplexity", []]
      # vary: ?["perplexity", list(range(100, 5000, 500)) if not test else []]
      kws:
        backend: null
    pacmap_tdr:
      vary: ["n_neighbors", []]
      # vary: ?["n_neighbors", list(range(100, 5000, 500)) if not test else [50, 100]]
      kws:
        backend: null

batch_key: "flowcell" # NOTE: it's called batch key, but we pass in "patient" so that the hgv routine genes for hcc subtypes
# TODO: this should be a key denoting the batch in which the samples were sent to the sequencing center. Probably set to flowcell for now

# * Feature selection
permissive_fs:
  method: seurat
  kws:
    layer: "lshift_normalized"
    inplace: false
    subset: false
    n_top_genes: 6000

feature_selection:
  seurat:
  # method:
  # cellranger:

# * Cluster fold similarity
do_cfs:
  cluster_exclude: ?this["exclude_from_clustering"]
  setup_kws:
    subset_hvgs: ?not test
    leiden_kws:
    pca_kws:
  cfs_kws:
    parallel: true

# * QC filtering
# NOTE: determine these after looking at QC plots
# Map below has the following structure: COLNAME: [<OUTLIER_LOW>, <OUTLIER_HIGH>]
# A cell is determined to be an outlier if its distance from the median in terms of MADs
# falls below OUTLIER_LOW or is greater than OUTLIER_HIGH. They can be set to null not
# to do filtering in that direction
mads_thresholds:
  n_genes_by_counts: [-2, null]
  pct_counts_mito: [null, 15]
  total_counts: [-1, null]

# * Normalization
normalization:
  normalize_total:
    # within_batch: true
    target_sum: null
    exclude_highly_expressed: false
  pooled_normalization:
  cluster_method: "scran"

# * Sample clustering
cluster_samples:
  features:
    default: null
  consensus_palette: null
  kws:
    maxK: 8
    reps: 1000
    distance: pearson

# * DE analyses
do_de_samples: # Takes the filtered data as input
  # BUG: [2026-02-24 Tue] this doesn't work for some reason
  # TODO: allow passing arbitrary contrasts
  edgeR_subtype:
    method: edgeR
    query: type == 'tumor' & treatment == 'control'
    kws:
      group: "default_4"
      batch_factors: ?this['batch_key']
  edgeR_iacs:
    method: edgeR
    query: type == 'tumor'
    kws:
      group: "treatment"
      contrasts:
        iacs_vs_ctrl: "treatmentiacs-treatmentcontrol"
      batch_factors: ?this['batch_key']
  scVI_subtype:
    method: scVI
    query: type == 'tumor' & treatment == 'control'
    kws:
      groupby: "default_4"
      batch_correction: true
  scVI_patient:
    method: scVI
    query: type == 'tumor' & treatment == 'control'
    # Use query to filter samples beforehand
    kws:
      groupby: "patient"
      batch_correction: true
      delta: 0.25 # Default delta
      fdr_target: 0.05 # Default fdr target
  scVI_tumor_vs_normal:
    query: treatment == 'control'
    method: scVI
    kws:
      groupby: type
      group1: tumor
      group2: normal
      batch_correction: true

# * Integration
integration:
  scVI: # https://docs.scvi-tools.org/en/stable/faq.html#what-is-the-difference-between-batch-key-and-categorical-covariate-keys
    kws:
      n_layers: 2
      n_latent: 30
      gene_likelihood: nb
      train_kws:
        max_epochs: ?None if not test else 40 # Rely on heuristic
  harmony:
    layer: "lshift_normalized"
    kws:
    # method:

train_scvi_permissive: ?this["integration"]["scVI"]

# * Cell clustering

cluster_cells:
  exclude: ?this["exclude_from_clustering"]
  method: leiden
  sweep: [0.01, 0.1, 0.5, 1]
  kws:
    random_state: ?this["rng"]

# * Gene set & marker resources

obs_markers_annotate:
  - LIN28B
  - GPC3
  - AFP
markers:

gene_sets:
gene_set_files: ?[f"{proj_root}/analyses/data/hcc_reference/gene_sets.yaml"]
marker_files: ?[f"{proj_root}/analyses/data/hcc_reference/cell_markers.yaml"]

# * Cell type annotation

dotplot:
  markers:
    main:
      - LIN28A
      - LIN28B
      - GPC3 # glypican 3
      - AFP # Alpha-fetoprotein
    mage:
      - MAGEA1
      - MAGEA2
      - MAGEA3
      - MAGEA11 # Found DE in clusters by edgeR
      - MAGEA4 # Found DE in clusters by edgeR
      - MAGEA8 # Found DE in clusters by edgeR
      - MAGEA9B # Found DE in clusters by edgeR
    stemness_tfs:
      - SOX2
      - NANOG
      - EPCAM
      - SALL4
      - POU5F1 # Oct4
      - KLF4
      - MYC # c-Myc
    stemness_surface:
      - CD44
      - CD133
      - CD117
    disco_cholangiocyte:
      - KRT7
      - KRT19
      - SPP1
      - ALB
      - SERPINA1
    edgeR_de:
      - OR14J1
      - PRTG
      - CARD18
      - CMKLR2
      - ZEB1
  kws:
    gene_symbols: hgnc_symbol
    cmap: "Greens"
    var_group_rotation: 90
    layer: null
    # layer: lshift_normalized
    log: false
    swap_axes: True
  totals_kws:
    color: "green"

cellassign:
  kws:
    layer: null # Cellassign uses counts
    size_factor_key: lshift_size_factors
    train_kws:
      batch_size: 1024
      max_epochs: ?30 if test else 400

# * Associated genes

find_gene_associations:
  keep: 15
  # TODO: see if adding a query actually makes a difference
  spec:
    - name: "main_set_cluster2"
      query: "default_4 == '2'"
      genes: ["LIN28B", "AFP", "GPC3"]
      group_by: "default_4"
    - name: "main_set_cluster2_no_subset"
      genes: ["LIN28B", "AFP", "GPC3"]
      group_by: "default_4"
    - name: "others_cluster1"
      query: "default_4 == '1'"
      genes: ["OR14J1", "ITIH3", "VCAM1"]
      group_by: "default_4"
    - name: "others_cluster3"
      query: "default_4 == '3'"
      genes: ["DUOXA2", "MMP1", "SLC28A3"]
      group_by: "default_4"
  kws:
    lr_transform: clr
    gene_col: null

# * Cluster annotation
# Only specified clusterings are used as input to the routine, determine by reviewing
# the cluster plots
chosen_clusters: # List of lists: [feature_selection, integration, cluster_name]
  leiden_res0.1: [seurat, scVI, leiden_res0.1]
  leiden_res0.01: [seurat, scVI, leiden_res0.01]

do_de_clusters:
  scVI:
    kws:
  edgeR:
    kws:
      p_value: 0.0001
      fc_cutoff: 1.2
      batch_factors: ["flowcell"]
    contrasts: # Mapping of keys in `chosen_clusters` to extra comparisons, in addition to one-vs-rest in clusters
      null
      # leiden_res0.5:
      #   - "(leiden_res0.50 + leiden_res0.512)/2 - (leiden_res0.51 + leiden_res0.52 + leiden_res0.53 + leiden_res0.54 + leiden_res0.55 + leiden_res0.56 + leiden_res0.57 + leiden_res0.58 + leiden_res0.59 + leiden_res0.510 + leiden_res0.511 + leiden_res0.513 + leiden_res0.514 + leiden_res0.515)/14" # The groups 0 and 12 are GPC3 positive

enrich_clusters:
  cutoff: 0.0001
  coverage: 0.95
  decouple_kws:
    methods: [ulm]
    layer: lshift_normalized
# mlm probably works like this:
# let feature i be the AFP gene. We model the observed statistic e.g. expression of AFP
# as expr(AFP) = intercept + beta_1x1 + beta_2x2 ...  + beta_px_p + error
# If x_i is 0 if AFP is not present in the ith feature set and 1 otherwise

gprofiler_enrich:
  scVI_min_proba_de: 0.8

# * Visualize DE & enrichment results
visualize_enrichment:
  palette_c: "ggthemes::Classic Red-Green Light"
  palette_d: "LaCroixColoR::CeriseLimon"

visualize_de_genes:
  scvi_min_prob: 0.8
  palette_c: "grDevices::Cyan-Magenta"
  always_include:
    - "GPC3"
    - "AFP"

# * Resources

gene_reference: ?f"{proj_root}/analyses/data/ensembl_gene_data.csv"
go_term2id: ?f"{proj_root}/analyses/data/go_term2id.csv"
go_graph: ?f"{proj_root}/analyses/data/go.gml"
reactome_pathways: ?"f{proj_root}/analyses/data/ReactomePathways.txt"
reactome_relations: ?"f{proj_root}/analyses/data/ReactomePathwaysRelation.txt"
tflink_mitab: ?f"{proj_root}/analyses/data/TFLink_Homo_sapiens_interactions_SS_mitab_v1.0.tsv"
reactome_fi: ?f"{proj_root}/analyses/data/FIsInGene_04142025_with_annotations.txt"
