__use_yte__: true
__definitions__:
  - from pathlib import Path
  - import sys
  - args = sys.argv
  - home = str(Path.home())
  - test = "test=True" in args
  - is_local = home.startswith("/home/shannc")
  - proj_root = f"{home}/Bio_SDD/chula-stem" if is_local else f"{home}/chula-stem"
  - data_root = f"{proj_root}/analyses/data_all" if is_local else "/data/project/stemcell/shannc"
  - workdir = f"{proj_root}/analyses/scrnaseq_hcc"
  - outdir = f"{data_root}/output/HCC/SCRNASEQ/cohort" if not test else f"{workdir}/test"

test: ?test

args: ?args
workdir: ?workdir
outdir: ?outdir
data_root: ?f"{data_root}/output/HCC/SCRNASEQ"
logdir: ?f"{proj_root}/analyses/scrnaseq_hcc/logs"
manifest: ?f"{this['workdir']}/manifest.csv"
gene_reference: ?f"{proj_root}/analyses/data/ensembl_gene_data.csv"

files:
  combined: ?f"{this['outdir']}/combined.h5ad"
  passed_qc: ?f"{this['outdir']}/filtered.h5ad"
  failed_qc: ?f"{this['outdir']}/failed_qc.h5ad"
  integrated: ?f"{this['outdir']}/integrated.h5ad"
  extras: # | character separates sample type
    HCC5|normal|control: ?f"{this['outdir']}/HCC5/processed/mnt-nas-thanakornj-liverOrganoid-SCTmatrix-HCC_N5_normal.h5ad"
    HCCN22|normal|control: ?f"{this['outdir']}/HCCN22/processed/mnt-nas-thanakornj-liverOrganoid-SCTmatrix-HCC_N22_normal.h5ad"
    HCCN1|normal|control: ?f"{this['outdir']}/HCCN1/processed/mnt-nas-thanakornj-liverOrganoid-SCTmatrix-HCC_N1_normal.h5ad"

rng: 4972

# * Dimensionality reduction
DR:
  n_pcs: 50
  methods:
    umap:
      vary: ?["n_neighbors", list(range(100, 5000, 500))]
      kws:
        backend: null
        init: "normal" # Default is "pca", but we pass in X PCA in the script already
    t-sne:
      vary: ?["perplexity", list(range(100, 5000, 500))]
      kws:
        backend: null
        init: "normal"
    # pacmap:
    # phate:
  outdirs:
    unintegrated: ?f"{this['outdir']}/DR_unintegrated"
    integrated: ?f"{this['outdir']}/DR_integrated"

# * QC filtering
# [2026-02-06 Fri] determined after looking at plots
# Map below has the following structure: COLNAME: [<OUTLIER_LOW>, <OUTLIER_HIGH>]
# A cell is determined to be an outlier if its distance from the median in terms of MADs
# falls below OUTLIER_LOW or is greater than OUTLIER_HIGH. They can be set to null not
# to do filtering in that direction
mads_thresholds:
  n_genes_by_counts: [-2, null]
  pct_counts_mito: [null, 15]
  total_counts: [-1, null]

# * Normalization
normalization:
  normalize_total:
    # within_batch: true
    target_sum: null
    exclude_highly_expressed: false
  pooled_normalization:
    cluster_method: "scran"

# * Gene group definitions

markers:
  main:
    - LIN28A
    - GPC3 # glypican 3
    - AFP # Alpha-fetoprotein

