__use_yte__: true
__definitions__:
  - from pathlib import Path
  - import sys
  - args = sys.argv
  - home = str(Path.home())
  - test = "test=True" in args
  - is_local = home.startswith("/home/shannc")
  - proj_root = f"{home}/Bio_SDD/chula-stem" if is_local else f"{home}/chula-stem"
  - tpredict = f"{home}/Bio_SDD/too-predict" if is_local else f"{home}/too-predict"
  - data_root = f"{proj_root}/analyses/data_all" if is_local else "/data/project/stemcell/shannc"
  - workdir = f"{proj_root}/analyses/scrnaseq_hcc"
  - outdir = f"{data_root}/output/HCC/SCRNASEQ/cohort" if not test else f"{workdir}/test"

test: ?test

manifest_file_key: null # Set to null to take from the cellranger directory
conda: stem-base
args: ?args
workdir: ?workdir
outdir: ?outdir
data_root: ?f"{data_root}/output/HCC/SCRNASEQ"
logdir: ?f"{workdir}/logs" if not test else f"{workdir}/test/logs"
manifest: ?f"{this['workdir']}/manifest.csv"
gene_reference: ?f"{proj_root}/analyses/data/ensembl_gene_data.csv"

exclude_from_clustering: # We're excluding normals and treated samples from clustering routines since the goal in those is to find tumor subtypes. Cells from these samples will have their cluster values set to NA
  - H19_tumor-iacs
  - H8_tumor-iacs
  - H8_tumor-oligomycin
  - H8_tumor-pp
  - HCCN1_normal-control
  - HCCN22_normal-control
  - HCC5_normal-control

files:
  combined: ?f"{this['outdir']}/combined.h5ad"
  permissive_features: ?f"{this['outdir']}/permissive_features.txt"
  passed_qc: ?f"{this['outdir']}/filtered.h5ad"
  failed_qc: ?f"{this['outdir']}/failed_qc.h5ad"
  extras: # | character separates sample type
    HCC5|normal|control: ?f"{data_root}/output/HCC/SCRNASEQ/HCC5/processed/mnt-nas-thanakornj-liverOrganoid-SCTmatrix-HCC_N5_normal.h5ad"
    HCCN22|normal|control: ?f"{data_root}/output/HCC/SCRNASEQ/HCCN22/processed/mnt-nas-thanakornj-liverOrganoid-SCTmatrix-HCC_N22_normal.h5ad"
    HCCN1|normal|control: ?f"{data_root}/output/HCC/SCRNASEQ/HCCN1/processed/mnt-nas-thanakornj-liverOrganoid-SCTmatrix-HCC_N1_normal.h5ad"

rng: 4972

# * Dimensionality reduction
DR:
  n_pcs: 50
  methods:
    umap:
      vary: ["n_neighbors", []]
      # vary: ?["n_neighbors", list(range(100, 5000, 500)) if not test else []]
      kws:
        backend: null
    t-sne:
      vary: ["perplexity", []]
      # vary: ?["perplexity", list(range(100, 5000, 500)) if not test else []]
      kws:
        backend: null
    pacmap:
      vary: ["n_neighbors", []]
      # vary: ?["n_neighbors", list(range(100, 5000, 500)) if not test else [50, 100]]
      kws:
        backend: null

batch_key: "flowcell" # NOTE: it's called batch key, but we pass in "patient" so that the hgv routine genes for hcc subtypes
# TODO: this should be a key denoting the batch in which the samples were sent to the sequencing center. Probably set to flowcell for now

# * Feature selection
permissive_fs:
  method: seurat
  kws:
    layer: "lshift_normalized"
    inplace: false
    subset: false
    n_top_genes: 6000

feature_selection:
  seurat:
  # method:
  # cellranger:

# * Cluster fold similarity
do_cfs:
  cluster_exclude: ?this["exclude_from_clustering"]
  setup_kws:
    subset_hvgs: ?not test
    leiden_kws:
    pca_kws:
  cfs_kws:
    parallel: true

# * QC filtering
# [2026-02-06 Fri] thresholds determined after looking at plots
# Map below has the following structure: COLNAME: [<OUTLIER_LOW>, <OUTLIER_HIGH>]
# A cell is determined to be an outlier if its distance from the median in terms of MADs
# falls below OUTLIER_LOW or is greater than OUTLIER_HIGH. They can be set to null not
# to do filtering in that direction
mads_thresholds:
  n_genes_by_counts: [-2, null]
  pct_counts_mito: [null, 15]
  total_counts: [-1, null]

# * Normalization
normalization:
  normalize_total:
    # within_batch: true
    target_sum: null
    exclude_highly_expressed: false
  pooled_normalization:
  cluster_method: "scran"

# * DE analyses
de_analysis: # Takes the filtered data as input
  scVI_subtype:
    method: scVI
    query: type == 'tumor' & treatment == 'control'
    # Use query to filter samples beforehand
    setup_name: scVI
    kws:
      setup_name: "" # name of a key in integration with scVI parameters
      groupby: "patient"
      mode: "change" # Either "vanilla" or "change". Latter relies on delta
      batch_correction: true
      delta: 0.25 # Default delta
      fdr_target: 0.05 # Default fdr target
  scVI_tumor_vs_normal:
    query: treatment == 'control'
    method: scVI
    kws:
      idx1: type == 'tumor'
      idx2: type == 'normal'
      mode: "change"
      batch_correction: true

  # TODO: add edgeR

# * Integration
integration:
  scVI: # https://docs.scvi-tools.org/en/stable/faq.html#what-is-the-difference-between-batch-key-and-categorical-covariate-keys
    kws:
      n_layers: 2
      n_latent: 30
      gene_likelihood: nb
      train_kws:
        max_epochs: ?None if not test else 40 # Rely on heuristic
  harmony:
    layer: "lshift_normalized"
    kws:
    # method:

integrate_and_cluster:
  cluster_exclude: ?this["exclude_from_clustering"]

  # * Clustering
clustering:
  method: leiden
  sweep: [1, 3, 5]
  kws:
    random_state: ?this["rng"]

# * Marker gene resources

markers:
  main:
    - LIN28A
    - GPC3 # glypican 3
    - AFP # Alpha-fetoprotein
gene_sets:
gene_set_files: ?[f"{proj_root}/analyses/data/hcc_reference/gene_sets.yaml"]
marker_files: ?[f"{proj_root}/analyses/data/hcc_reference/cell_markers.yaml"]

# * Cell type annotation
chosen_cluster_key: null
# Set this once clusters have been evaluated and a specific clustering is chosen

dotplot:
  markers:
  kws:
    gene_symbols: hgnc_symbol
    cmap: "Greens"
    layer: null
    # layer: lshift_normalized
    log: false
    swap_axes: True
  totals_kws:
    color: "green"

cellassign:
  kws:
    layer: null # Cellassign uses counts
    size_factor_key: lshift_size_factors
    train_kws:
      batch_size: 1024
      max_epochs: ?50 if test else 400
