configfile: "cellranger_config.yaml"


combined_file = config["files"]["combined"]
permissive_features = config["files"]["permissive_features"]
passed_qc = config["files"]["passed_qc"]
logdir = config["logdir"]
outdir = config["outdir"]
anno_out = f"{outdir}/annotations"

from functions import provide_output_from_fs, provide_annotation_output

gpu_res20 = {
    "mem": "50G",
    "qos": "gpu20gh",
    "gres": "gpu:3g.20gb:1",
    "slurm_partition": "gpu",
}
gpu_res40 = {
    "mem": "64G",
    "qos": "gpu40g",
    "gres": "gpu:7g.40gb:1",
    "slurm_partition": "gpu",
}

if config["test"]:
    gpu_res20 = {}
    gpu_res40 = {}

dr_use_cpu = {"umap", "t-sne"}

other_outs = {}
feature_selection_methods = config["feature_selection"].keys()
for fs in feature_selection_methods:
    other_outs.update(provide_output_from_fs(fs, config))
other_outs.update(provide_annotation_output(config))

sample_cluster_keys = config["cluster_samples"]["features"].keys()
sample_cluster_out = [
    f"{outdir}/sample_clusters.csv",
    f"{outdir}/sample_clusters.pdf",
    f"{outdir}/sample_clusters_consensus.pdf",
]

if config.get("plots", False):
    other_outs = {
        k: v
        for k, v in other_outs.items()
        if k.endswith("PLOT") or k.startswith("cellassign")
    }


rule all:
    input:
        passed_qc,
        permissive_features,
        f"{outdir}/qc",
        *sample_cluster_out,
        **other_outs,


rule prepare_data:
    output:
        combined_file,
        permissive_features,
    script:
        "smk.py"


# TODO: should also add doublet detection and removal
rule qc_filter:
    input:
        combined_file,
    output:
        passed=passed_qc,
        failed=config["files"]["failed_qc"],
    log:
        f"{logdir}/qc.log",
    run:
        import anndata as ad
        import scanpy as sc
        from functions import mads_filter_outliers

        combined = ad.read_h5ad(input[0])

        passed, failed = mads_filter_outliers(
            combined, filters=config["mads_thresholds"], reduction="all"
        )
        print("Original shape: {}".format(combined.shape))
        print("Shape of filtered: {}".format(passed.shape))
        print("Shape of failed: {}".format(failed.shape))
        passed.write_h5ad(output["passed"])
        failed.write_h5ad(output["failed"])


rule do_dimensionality_reduction:
    input:
        lambda wc: (
            other_outs[f"{wc.get('fs_name')}-{wc.get('integration')}"]
            if wc.get("integration") != "unintegrated"
            else passed_qc
        ),
    params:
        dr_method=lambda wc: wc.get("method"),
        integration_method=lambda wc: wc.get("integration"),
        hp_value=lambda wc: wc.get("val"),
    log:
        f"{logdir}/{{fs_name}}_DR_{{integration}}/{{method}}/{{method}}_{{val}}.log",
    resources:
        gres=lambda wc: None if wc.get("method") in dr_use_cpu else "gpu:7g.40gb:1",
        slurm_partition=lambda wc: "cpu" if wc.get("method") in dr_use_cpu else "gpu",
        mem=lambda wc: "100G" if wc.get("method") in dr_use_cpu else "64G",
        qos=lambda wc: "cpu24h" if wc.get("method") in dr_use_cpu else "gpu40g",
    output:
        f"{outdir}/{{fs_name}}/DR_{{integration}}/{{method}}/{{method}}_{{val}}.npy",
    script:
        "smk.py"


# * Clustering and integration


rule do_cfs:
    input:
        passed_qc,
    log:
        f"{logdir}/cfs/{{fs_name}}.log",
    output:
        similarity=f"{outdir}/{{fs_name}}/cfs/similarity.csv",
        communities=f"{outdir}/{{fs_name}}/cfs/communities.csv",
        ind_clustering=f"{outdir}/{{fs_name}}/cfs/ind_clustering.csv",
    script:
        "smk.R"


rule integrate:
    input:
        passed_qc,
    log:
        f"{logdir}/{{fs_name}}-integration_and_cluster_{{integration}}.log",
    params:
        feature_selection=lambda wc: wc.get("fs_name"),
        integration=lambda wc: wc.get("integration"),
    resources:
        **gpu_res20,
    output:
        f"{outdir}/{{fs_name}}/{{integration}}_integrated.h5ad",
    script:
        "smk.py"


rule cluster_cells:
    input:
        passed_qc,
        f"{outdir}/{{fs_name}}/{{integration}}_integrated.h5ad",
    params:
        integration=lambda wc: wc.get("integration"),
    output:
        f"{outdir}/{{fs_name}}/{{integration}}_clustering.h5ad",
    script:
        "smk.py"


rule mark_cluster_complete:
    input:
        expand(
            f"{outdir}/{{f}}/{{i}}_clustering.h5ad",
            f=feature_selection_methods,
            i=config["integration"].keys(),
        ),
    output:
        f"{outdir}/.clustering_complete",
    shell:
        "touch {output}"


rule train_scvi_permissive:
    input:
        passed_qc,
        permissive_features,
    resources:
        **gpu_res40,
    output:
        path=directory(f"{outdir}/scVI_permissive"),
    script:
        "smk.py"


# * DE analysis


rule cluster_samples:
    input:
        passed_qc,
        features=lambda wc: permissive_features if wc.get("fs") == "default" else [],
    params:
        prefix=lambda wc: wc.get("fs"),
    output:
        f"{outdir}/.sample_clusters/{{fs}}.csv",
        f"{outdir}/.sample_clusters/{{fs}}_consensus.pdf",
    script:
        "smk.R"


rule gather_sample_clusters:
    input:
        clusters=expand(f"{outdir}/.sample_clusters/{{fs}}.csv", fs=sample_cluster_keys),
        plots=expand(
            f"{outdir}/.sample_clusters/{{fs}}_consensus.pdf", fs=sample_cluster_keys
        ),
        adata=passed_qc,
    output:
        f"{outdir}/sample_clusters.csv",
        f"{outdir}/sample_clusters_consensus.pdf",
    script:
        "smk.py"


rule do_de_samples:
    input:
        adata=passed_qc,
        features=permissive_features,
        clusters=f"{outdir}/sample_clusters.csv",
        model=lambda wc: (
            f"{outdir}/scVI_permissive"
            if config["do_de_samples"][wc.get("spec")].get("method") == "scVI"
            else []
        ),
    params:
        spec=lambda wc: wc.get("spec"),
    output:
        f"{anno_out}/.sample_de-{{spec}}.csv",
    script:
        "smk.py"


rule gather_de_samples:
    input:
        expand(
            f"{anno_out}/.sample_de-{{spec}}.csv",
            spec=config["do_de_samples"].keys(),
        ),
    output:
        f"{anno_out}/samples_de.csv",
    run:
        import pandas as pd

        tmp = []
        for csv in input:
            spec = Path(csv).stem.replace(".sample_de-", "")
            df = pd.read_csv(csv).assign(analysis_group=spec)
            if spec.startswith("edgeR") and "logFC" in df.columns:
                df.loc[:, "lfc"] = df["logFC"]
            elif spec.startswith("scVI"):
                if "lfc_median" in df.columns:
                    df.loc[:, "lfc"] = df["lfc_median"]
                if "contrast" not in df.columns:
                    df.loc[:, "contrast"] = df["analysis_group"].str.removeprefix(
                        "scVI_"
                    )
            tmp.append(df)
        pd.concat(tmp).to_csv(output[0], index=False)


# * Annotation routines

# NOTE: don't need feature selection for cell assign because it will automatically
# subset features


rule cellassign:
    input:
        passed_qc,
    params:
        model=f"{outdir}/cellassign",
    resources:
        **gpu_res40,
    output:
        predictions=other_outs["cellassign_predictions"],
        run_metrics=other_outs["cellassign_run_metrics"],
    script:
        "smk.py"


rule enrich_clusters:
    input:
        passed_qc,
        f"{outdir}/.clustering_complete",
    output:
        f"{outdir}/annotations/clusters_gene_set_activity.csv",
        f"{outdir}/annotations/clusters_marker_gene_activity.csv",
    resources:
        mem="50G",
    script:
        "smk.py"


rule do_de_clusters:
    input:
        adata=passed_qc,
        check=f"{outdir}/.clustering_complete",
        features=permissive_features,
        model=lambda wc: (
            f"{outdir}/scVI_permissive" if wc.get("method") == "scVI" else []
        ),
    params:
        method=lambda wc: wc.get("method"),
        outdir=anno_out,
    output:
        f"{anno_out}/clusters-{{method}}_de.csv",
    script:
        "smk.py"


# Enrich DE genes with gprofiler
rule gprofiler_enrich:
    input:
        sample_level=f"{anno_out}/samples_de.csv",
        cluster_level=expand(
            f"{anno_out}/clusters-{{method}}_de.csv",
            method=["scVI", "edgeR"],
        ),
    output:
        cluster_level=f"{anno_out}/clusters_de_gprofiler.csv",
        sample_level=f"{anno_out}/samples_de_gprofiler.csv",
    script:
        "smk.py"


# * Plotting
rule save_other_dotplots:
    input:
        **rules.do_cfs.output,
        **rules.cellassign.output,
        adata=passed_qc,
    params:
        feature_selection=lambda wc: wc.get("fs_name"),
    output:
        f"{outdir}/{{fs_name}}/dotplots.pdf",
        f"{outdir}/{{fs_name}}/cellassign_metrics.pdf",
    script:
        "smk.py"


rule save_sample_dotplots:
    input:
        clusters=expand(f"{outdir}/.sample_clusters/{{fs}}.csv", fs=sample_cluster_keys),
        adata=passed_qc,
    output:
        f"{outdir}/sample_clusters.pdf",
    script:
        "smk.py"


rule save_cluster_plots:
    input:
        passed_qc,
        f"{outdir}/{{fs_name}}/{{integration}}_clustering.h5ad",
    output:
        f"{outdir}/{{fs_name}}/{{integration}}_clustering.pdf",
    params:
        fs_name=lambda wc: wc.get("fs_name"),
        integration=lambda wc: wc.get("integration"),
    run:
        import anndata as ad
        import functions as fn

        adata = ad.read_h5ad(input[0])
        fn.make_cluster_dotplots(
            adata,
            filename=output[0],
            cluster_results=input[1],
            markers={},
            env=config,
        )


rule save_qc_plots:
    input:
        combined_file,
    output:
        directory(f"{outdir}/qc"),
    run:
        from functions import qc_plot_patient
        from pathlib import Path
        import anndata as ad

        outdir = Path(output[0])
        outdir.mkdir(exist_ok=True)

        combined = ad.read_h5ad(input[0])
        for patient in combined.obs["patient"].unique():
            qc_mads, mads_compare = qc_plot_patient(combined, patient)
            (qc_mads / mads_compare).save(outdir / f"{patient}.pdf")


        """
Produces two plots
1. Regulatory networks provided by TFlink containing DE genes
2. Functional interaction networks from Reactome (excluding regulatory interactions)
    containing DE genes
"""


# TODO: [2026-02-24 Tue] custom plots with ggraph, from the results of the GO
# and pathway enrichment analyses, and well as DE
# rule visualize_pathways:
rule visualize_de_genes:
    input:
        cluster_level_scvi=f"{anno_out}/clusters-scVI_de.csv",
        cluster_level_edger=f"{anno_out}/clusters-edgeR_de.csv",
        sample_level=f"{anno_out}/samples_de.csv",
    params:
        outdir=f"{anno_out}/de_plots",
    output:
        directory(f"{anno_out}/de_plots"),
    script:
        "smk.R"


# rule visualize_enriched:
