configfile: "cellranger_config.yaml"


combined_file = config["files"]["combined"]
passed_qc = config["files"]["passed_qc"]
integrated = config["files"]["integrated"]
logdir = config["logdir"]

gpu_res = {
    "mem": "30G",
    "qos": "gpu20gh",
    "gres": "gpu:3g.20gb:1",
    "slurm_partition": "gpu",
}
if config["test"]:
    gpu_res = {}

dr_results = {}
dr_cfg = config["DR"]
for o, p in dr_cfg["outdirs"].items():
    dr_results[o] = {}
    for method, values in dr_cfg["methods"].items():
        v = values["vary"][1]
        dr_results[o][f"dr_{o}_{method}"] = expand(
            f"{p}/{method}/{method}_{{v}}.npy", v=v
        )

cfs_results = {
    "similarity": f"{config["outdir"]}/cfs/similarity.csv",
    "communities": f"{config["outdir"]}/cfs/communities.csv",
    "independent_clustering": f"{config["outdir"]}/cfs/ind_clustering.csv",
}


rule all:
    input:
        passed_qc,
        integrated,
        **dr_results["unintegrated"],
        **dr_results["integrated"],
        **cfs_results,


rule prepare_data:
    output:
        combined_file,
    script:
        "smk.py"


# TODO: should also add doublet detection and removal
rule qc_filter:
    input:
        combined_file,
    output:
        passed=passed_qc,
        failed=config["files"]["failed_qc"],
    log:
        f"{logdir}/qc.log",
    run:
        import anndata as ad
        import scanpy as sc
        from functions import mads_filter_outliers

        combined = ad.read_h5ad(input[0], backed=True)

        passed, failed = mads_filter_outliers(
            combined.to_memory(), filters=config["mads_thresholds"], reduction="all"
        )
        print("Original shape: {}".format(combined.shape))
        print("Shape of filtered: {}".format(passed.shape))
        print("Shape of failed: {}".format(failed.shape))
        passed.write_h5ad(output["passed"])
        failed.write_h5ad(output["failed"])


for name, path in dr_cfg["outdirs"].items():
    if name == "unintegrated":
        in_adata = passed_qc
    else:
        in_adata = integrated

    rule do_dimensionality_reduction:
        input:
            in_adata,
        name:
            f"do_dimensionality_reduction_{name}"
        params:
            method=lambda wc: wc.get("method"),
            hp_value=lambda wc: wc.get("val"),
        log:
            f"{logdir}/DR/{{method}}/{{method}}_{{val}}.log",
        resources:
            **gpu_res,
        output:
            f"{path}/{{method}}/{{method}}_{{val}}.npy",
        script:
            "smk.py"


# TODO: just need to test it
rule cluster_fold_similarity:
    input:
        passed_qc,
    log:
        f"{logdir}/cluster_fold_similarity.log",
    output:
        **cfs_results,
    script:
        "smk.R"


rule integrate_and_cluster:
    input:
        passed_qc,
    log:
        f"{logdir}/integration_and_cluster.log",
    resources:
        **gpu_res,
    output:
        integrated,
    script:
        "smk.py"
