configfile: "cellranger_config.yaml"


combined_file = config["files"]["combined"]
permissive_features = config["files"]["permissive_features"]
passed_qc = config["files"]["passed_qc"]
logdir = config["logdir"]
outdir = config["outdir"]

from functions import provide_output_from_fs

gpu_res = {
    "mem": "30G",
    "qos": "gpu20gh",
    "gres": "gpu:3g.20gb:1",
    "slurm_partition": "gpu",
}
if config["test"]:
    gpu_res = {}


if config["chosen_cluster_key"]:
    anno_res = {
        "cell_assign": {
            "predictions": f"{outdir}/cellassign_predictions.csv",
            "run_metrics": f"{outdir}/cellassign_metrics.csv",
        },
        "anno_dotplot": [],
    }
else:
    anno_res = {}

other_outs = {}
for fs_method in config["feature_selection"].keys():
    other_outs.update(provide_output_from_fs(fs_method, config))


rule all:
    input:
        passed_qc,
        permissive_features,
        **other_outs,


rule prepare_data:
    output:
        combined_file,
        permissive_features,
    script:
        "smk.py"


# TODO: should also add doublet detection and removal
rule qc_filter:
    input:
        combined_file,
    output:
        passed=passed_qc,
        failed=config["files"]["failed_qc"],
    log:
        f"{logdir}/qc.log",
    run:
        import anndata as ad
        import scanpy as sc
        from functions import mads_filter_outliers

        combined = ad.read_h5ad(input[0], backed=True)

        passed, failed = mads_filter_outliers(
            combined.to_memory(), filters=config["mads_thresholds"], reduction="all"
        )
        print("Original shape: {}".format(combined.shape))
        print("Shape of filtered: {}".format(passed.shape))
        print("Shape of failed: {}".format(failed.shape))
        passed.write_h5ad(output["passed"])
        failed.write_h5ad(output["failed"])


rule do_dimensionality_reduction:
    input:
        lambda wc: (
            other_outs[f"{wc.get('fs_name')}-{wc.get('integration')}"]
            if wc.get("integration") != "unintegrated"
            else passed_qc
        ),
    params:
        dr_method=lambda wc: wc.get("method"),
        integration_method=lambda wc: wc.get("integration"),
        hp_value=lambda wc: wc.get("val"),
    log:
        f"{logdir}/{{fs_name}}_DR_{{integration}}/{{method}}/{{method}}_{{val}}.log",
    resources:
        **gpu_res,
    output:
        f"{outdir}/{{fs_name}}/DR_{{integration}}/{{method}}/{{method}}_{{val}}.npy",
    script:
        "smk.py"


# TODO: just need to test it
rule do_cfs:
    input:
        passed_qc,
    log:
        f"{logdir}/cfs/{{fs_name}}.log",
    output:
        similarity=f"{outdir}/{{fs_name}}/cfs/similarity.csv",
        communities=f"{outdir}/{{fs_name}}/cfs/communities.csv",
        ind_clustering=f"{outdir}/{{fs_name}}/cfs/ind_clustering.csv",
    script:
        "smk.R"


rule integrate_and_cluster:
    input:
        passed_qc,
    log:
        f"{logdir}/{{fs_name}}-integration_and_cluster_{{integration}}.log",
    params:
        feature_selection=lambda wc: wc.get("fs_name"),
        integration=lambda wc: wc.get("integration"),
    resources:
        **gpu_res,
    output:
        integrated=f"{outdir}/{{fs_name}}/{{integration}}_integrated.h5ad",
        clustering=f"{outdir}/{{fs_name}}/{{integration}}_clustering.h5ad",
    script:
        "smk.py"


# * Cell type annotation

# NOTE: don't need feature selection for cell assign because it will automatically
# subset features


rule cellassign:
    input:
        passed_qc,
    params:
        model=f"{outdir}/cellassign",
    output:
        **anno_res.get("cellassign", {}),
    script:
        "smk.py"
